name: app_strings
description: Comprehensive Package for Managing Multilingual Application Strings
version: 1.2.3
repository: https://github.com/EFA-dev/app_strings

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  build: ^4.0.0
  source_gen: ^4.0.1
  code_builder: ^4.11.0
  dart_style: ^3.1.2
  built_collection: ^5.1.1
  analyzer: ^8.1.1
  meta: ^1.16.0
  path: ^1.9.1


dev_dependencies:
  build_runner: ^2.8.0  
  lints: ^6.0.0
  test: ^1.26.2
  