name: app_strings
description: Comprehensive Package for Managing Multilingual Application Strings
version: 1.3.0
repository: https://github.com/EFA-dev/app_strings

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  build: ^4.0.3
  source_gen: ^4.1.1
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  built_collection: ^5.1.1
  analyzer: ^9.0.0
  meta: ^1.17.0
  path: ^1.9.1


dev_dependencies:
  build_runner: ^2.10.4  
  lints: ^6.0.0
  test: ^1.28.0
  